/*
 * Configuracoes.java
 *
 * Created on February 10, 2008, 6:09 PM
 */
package derplayer.gui;

import derplayer.Configuracao;
import derplayer.Main;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
@author  Andoreh
 */
public class Configuracoes extends javax.swing.JFrame {

    private static Configuracoes instanciaAtual;

    /** Creates new form Configuracoes */
    public Configuracoes() {
        initComponents();
        preencherValores();

    }

    public static void exibir() {
        if (instanciaAtual == null) {
            instanciaAtual = new Configuracoes();
        }
        instanciaAtual.setVisible(true);
    }

    /** This method is called from within the constructor to
    initialize the form.
    WARNING: Do NOT modify this code. The content of this method is
    always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chExibirTocando = new javax.swing.JCheckBox();
        chExibirErroTag = new javax.swing.JCheckBox();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setTitle("Configurações");
        setBounds(getPosicao());
        setIconImage(Main.getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações"));

        chExibirTocando.setText("Exibir a música que está tocando no momento");

        chExibirErroTag.setText("Exibir alerta quando for detectado erro nas tags");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chExibirTocando)
                    .addComponent(chExibirErroTag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chExibirTocando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chExibirErroTag)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        preencherValores();
        this.setVisible(false);
}//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Configuracao config = Main.getConfiguracao();
        config.setExibirErroTags(chExibirErroTag.isSelected());
        config.setExibirMuisca(chExibirTocando.isSelected());
        Main.salvarConfiguracoes();
        this.setVisible(false);
    }//GEN-LAST:event_btSalvarActionPerformed

    private Rectangle getPosicao() {
        int largura = 305;
        int altura = 141;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Rectangle retorno = new Rectangle((int) screenSize.getWidth() - largura - 10, (int) screenSize.getHeight() - altura - 62, largura, altura);
        return retorno;
    }

    private void preencherValores() {
        Configuracao config = Main.getConfiguracao();
        chExibirErroTag.setSelected(config.isExibirErroTags());
        chExibirTocando.setSelected(config.isExibirMuisca());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox chExibirErroTag;
    private javax.swing.JCheckBox chExibirTocando;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
